### ISSUE TITLE
Location of Drivers for the different services

### ISSUE THREAD

**Issue by mgvinuesa** [cloudfoundry-community/tomee-buildpack-resource-configuration#7]
Hi,

I'm deploying an EAR application with two WARs in Cloud Foundry using tomEE buildpack.
Every webapp application is bound to a DB service, in this cases two ClearDB services.

I suppose that I have to provide the drivers to make the connection properly but I have tried every possible location (I think)

I have the following error:

```
2018-02-14T20:14:41.998+01:00 [APP/PROC/WEB/0] [OUT] Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.OpenEJBException: Failed Configuring Service(id=ROOT/jdbc/ARQRUNDataSource): Error calling instance factory method: public java.util.Properties org.cloudfoundry.reconfiguration.tomee.DelegatingPropertiesProvider.provides()

...

2018-02-14T20:14:41.999+01:00 [APP/PROC/WEB/0] [OUT] Caused by: org.cloudfoundry.reconfiguration.tomee.ConfigurationException: Cannot find suitable driver for MysqlServiceInfo[mysql://<SQL CONNECTION>]
2018-02-14T20:14:41.999+01:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.tomee.provider.MySqlProperiesProvider.getJdbcDriverClass(MySqlProperiesProvider.java:53)
2018-02-14T20:14:41.999+01:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.tomee.provider.MySqlProperiesProvider.configure(MySqlProperiesProvider.java:36)
2018-02-14T20:14:41.999+01:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.reconfiguration.tomee.provider.RelationalServicePropertiesProvider.provide(RelationalServicePropertiesProvider.java:129)
```
The mysql driver has been located inside the WAR (WEB-INF/lib) and the EAR(APP-INF/lib) but I suppose seeing this [picture ](https://github.com/cloudfoundry-community/tomee-buildpack-resource-configuration/blob/master/docs/resource_configuration.png)that the classpath is not accesible yet when the reconfiguration happen.

Where do I have to deploy this libs?

**Comment by violetagg** [comment]
Hi,

Put the drivers in the `EAR_HOME/drivers` 
https://github.com/cloudfoundry-community/tomee-buildpack/blob/master/docs/container-tomee.md#support-for-deploying-an-ear-enterprise-application-archive-file

Regards,
Violeta

**Comment by mgvinuesa** [comment]
Hi,

It works perfectly. thanks.
